<?php

function meego_master_profile_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_profile_form' || $form_id == 'user_register') {
    foreach (element_children($form) as $key => $element) {
      if (substr($element, 0, 10) == 'conference') {
        $form[$element]['#access'] = FALSE;
      }
    }
  }
}

/*
 * Implementation of hook_menu_alter().
 */
function meego_master_profile_menu_alter(&$items) {
  $items['user/%user/edit/Conference Information']['access callback'] = FALSE;
}
