<?php

/*
 * Implementation of hook_block().
 */
function meego_site_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0]['info'] = t('Call to action: Sign up for the conference');
    return $blocks;
  }
  
  if ($op == 'view') {
    switch ($delta) {
      case 0:
        global $user;
        $block['subject'] = '';
        // Don't show the block to anonymous users. They get their own call to action.
        if (empty($user->uid)) {
          return $block;
        }
        $sid = db_result(db_query("SELECT sid FROM {signup_log} WHERE nid = 1 AND uid = %d", $user->uid));
        // They've already signed up. Don't remind them again.
        if (!empty($sid)) {
          return $block;
        }
        $node = node_load(1);
        $block['subject'] = t('MeeGo Conference Sign-up');
        $block['content'] = t("Sign-up to attend the MeeGo Conference in Dublin, Ireland November 15-17th, 2010! This free three day conference is open to all who are interested in MeeGo platform and application development.");
        module_load_include('inc', 'signup', 'includes/node_output');
        $block['content'] .= _signup_node_output($node);
        return $block;
    }
  }
}

/**
 * Implement hook_signup_data_alter().
 * Automatically assign attendees the correct status baed on their organization.
 */
function meego_site_signup_data_alter(&$signup, $form_values) {
  if (!empty($signup->mail)) {
    if(strpos($signup->mail, 'intel.com') || strpos($signup->mail, 'nokia.com')) {
      $signup->status = 3;
    }
  }
}